### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by TomTheDragon** [fchat-pidgin/fchat-pidgin#68] opened 2015-09-29 00:34 UTC
I wanted to try out the search function after some while but it seams to be broken under Windows (8.1 x64).
When i try to enter something in the search window, i just see as a second window flashing up for a moment but nothing happens.

I also notice a different bug when i tried to search under LinuxMint (17.2 x64).
The search itself is working fine but it seems that the limit for the search results is gone. I noticed this as Pidgin tried to add 3000+ users as temporary buddies to my Pidgin which resulted in a timeout.

The version i am using is v0.5.0-24-gc3c9b2c

**Comment by vobe** [comment] 2015-10-01 07:45
I could not reproduce this issue on Windows 8.1 x64, can you provide screenshots of the steps that produce this error, as well as a copy of anything that appears in the debug window when the bug happens ?

As for the search limit issue, please open another issue so we don't get things mixed up. I don't see any form of search result limitation in the code, do you remember which version had such a limit ?

**Comment by TomTheDragon** [comment] 2015-10-04 01:35
The problem seems to come from the updated gtk+ bundle i use, i updated it to the newest v2.24.10. I had to do this because of some other plugins (the skypeweb one for example) that did crash with the old gtk+ bundle that comes with Pidgin. I tested this with two accounts and there are no errors to see in the console.

I also did some other tests and the limit problem only occurs when you dont set one of the kink filters, if you set at least one of them, you will get an "There are too many search results, please narrow your search" error.

**Comment by vobe** [comment] 2016-09-09 16:58
Closing this because one half of this issue was fixed and the other only affects one particular, non-bundled GTK version.

**Closed by vobe** 2016-09-09 16:58 UTC
Labels: bug, win32
