### ISSUE TITLE
Place friends and bookmarked characters in different groups by default

### ISSUE THREAD

**Issue by alexolog** [fchat-pidgin/fchat-pidgin#148] opened 2016-09-30 21:55 UTC
Currently, they are both placed into the "friends" group.

Also, remove them form that group if the user removes the bookmark or "unfriends" them.

**Comment by vobe** [comment] 2016-09-30 22:08
Duplicate of #56 and #117. I guess I should get working on that soon then :p

**Closed by vobe** 2016-09-30 22:08 UTC
