### ISSUE TITLE
Double Post Display

### ISSUE THREAD

**Issue by ringtailedfox** [fchat-pidgin/fchat-pidgin#150] opened 2016-12-09 23:38 UTC
When I type a message and send it in the Pidgin plugin, Pidgin displays my  message as being sent twice, such as:
(5:54:15 PM) ***ringtailedfox waves hello!
(5:54:15 PM) ***ringtailedfox waves hello!

I'm running Windows 10 Professional 64-bit Edition with Pidgin 2.11.0 and the latest version of FChat-Pidgin (0.6.0).  This only occurs when the "Message Splitter" plugin is also enabled, regardless of the length of message on FChat.  While this can be fixed by disabling the Message Splitter plugin, I would like to see if there's a way to fix this interference or conflict...

**Comment by vobe** [comment] 2016-12-09 23:44
This is a duplicate of #110 and I'm really not sure how to fix it without changing the message splitter plugin

**Closed** 2016-12-09 23:45 UTC
Labels: duplicate

**Comment by ringtailedfox** [comment] 2016-12-10 00:13
Whoops, sorry! i didn't know this was already referenced.  my apologies! :)
